import type { Metadata } from "next";
import "./globals.css";
import 'highlight.js/styles/github.css';

// 其他导入和组件代码...

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}




export const metadata: Metadata = {
  title: "Kafka's Blog",
  description: "Generated by create next app",
};


